travis:
  secure:
    BINSTAR_TOKEN: u+Q7uXkIN7jIoJHeCcDy9WaD0IYAhzQDMJe2bQNEB9NHKT/wC7cLVoiuhJRBhLrWMcEGgZovRuuP9ffZNbNSXVxhVPd5x+u28Jq58O9usZhVCvUmuauv5Jp+Qo17Sc5FJst2UCNo9gBFX5ilTV0fMTn0TPffYRY9kCQpEyUPd6H26upzIseAI4P1aB7yTubQe/nqUuyRk0+xD9Db6wLG7glgrMTUD6wPVcd7XCUszzBqjQ0c/N5T/N3c8+oWa3pgWa/2tDix0tgk4taOgLU4lXzFnGEYDfmaTvebatmck7yPkxA4lW1/dj52cXPHJWk149ukqc0Tafbhts8Ge3c6CdKGvE+orY9paTbB9M6k5bC0GWt1Mxerj6GqK1NH0Pi5egXao+ATmj6UQzmHf17gYYPpmTCV0WVDGjLVTwcG6mH/7AfyBYDnsEPBV36mW3hhGV0oVYL3fIxY+5ys8Fp+fX/4E1SBOrFHDg+WZ7V57XgIJ+mIlXhHDDo3UEHvaxLrFlIK+dLFWEIKZOkB8b91BDCq86V53Z01pTubje458kkhvrz1Z6c9wfRywzez1ozD35kflmo1xDvxuTzMOu30MS/SBgpkIztHjEG+dmS+kP99Ja0i03tDNcGG3CY+uRkHC+9nqJHbLL2gmI3kOXZDbOMYTKCyFMvfD+GiCCp2HaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
